### ISSUE TITLE
你去github上搜索  ccks 2021 task2。看看里面的项目有没有数据，如果没有的话我给你发。------------------&nbsp;原始邮件&nbsp;------------------

### ISSUE THREAD

**Issue by 1508224326** [yihenglu/chinese-address-segment#8]
你去github上搜索  ccks 2021 task2。看看里面的项目有没有数据，如果没有的话我给你发。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月24日(星期二) 上午9:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yihenglu/chinese-address-segment] 数据 (#2)

您好，大佬 可以给我发一份吗？麻烦了1508224326@qq.com

**Comment by azhe1234** [comment]
> 你去github上搜索 ccks 2021 task2。看看里面的项目有没有数据，如果没有的话我给你发。------------------ 原始邮件 ------------------ _**@**_._**> 发送时间: 2021年8月24日(星期二) 上午9:29 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [yihenglu/chinese-address-segment] 数据 (#2)
> 
> 您好，大佬 可以给我发一份吗？麻烦了[1508224326@qq.com](mailto:1508224326@qq.com)

您好，兄弟，可以发一份这个数据集给我吗1243087862@qq.com谢谢
